### ISSUE TITLE
optnet.removeOptimization(net) not working

### ISSUE THREAD

**Issue by Guim3** [fmassa/optimize-net#25]
Hi, I have this network, which is already optimized by optnet:
[celeba_24_G.t7.zip](https://github.com/fmassa/optimize-net/files/562804/celeba_24_G.t7.zip)

And I want to remove the optimization in order to perform a backward pass.
When I do so, this happens:

```lua
optnet/init.lua:358: attempt to index local 'info' (a nil value)
stack traceback:
lua/5.1/optnet/init.lua:358: in function 'callback'
lua/5.1/nn/Module.lua:318: in function 'apply'
lua/5.1/nn/Module.lua:322: in function 'apply'
lua/5.1/optnet/init.lua:353: in function 'addGradParams'
lua/5.1/optnet/init.lua:444: in function 'removeOptimization'
```

This is a simplifcation of the code I run:
```lua
require 'image'
require 'nn'
require 'cudnn'
optnet = require 'optnet'
torch.setdefaulttensortype('torch.FloatTensor')

-- This network is already optimized
net = torch.load('celeba_24_G.t7')

optnet.removeOptimization(net)

-- Perform backpropagation stuff
net:updateGradInput(...)
```

How can I solve this?

Thanks.

**Comment by fmassa** [comment]
Hi,

For some reason, the tensor pointers that were saved in the network changed after the optimization was done, probably because there was a `cuda` or `float` conversion that happened after the optimization was performed.

The following snippet should allow you to recover you network without optimization:
https://gist.github.com/fmassa/e44159d86340a8a4ee7adfbc0fba60ed

If for some reason it doesn't work, here is a simplified version that supposes that there is no sharing of the `gradParameters` of the network that were made during construction:

```lua
local optnet = require 'optnet'
local net = torch.load('celeba_24_G.t7')

-- simply restore the gradParams to have
-- the same size as the parameters
local p, gp = net:parameters()
for k, v in ipairs(p) do
  gp[k]:resizeAs(v)
end

-- remove the extra things added by optnet
net.__gradParamsInfo = nil
net:apply(function(m)
  m.getParameters = nil
end)

optnet.removeOptimization(net)
```

**Comment by Guim3** [comment]
The snippet solved the issue. Thank you very much!
