### ISSUE TITLE
training mode memory use

### ISSUE THREAD

**Issue by shane-huang** [fmassa/optimize-net#28]
I used the given examples and turned on the training mode, and then count the memory before and after. But I got result as below. The mem use  after optimization is even bigger? This happens only on training mode. Evaluation mode is normal. 
```
Before optimization        : 291.81713867188 MBytes
After optimization         : 552.31911468506 MBytes
After removing optimization: 291.81716156006 MBytes
```  
Below is the code I use. 
```
models = require 'optnet.models'
modelname = 'googlenet'
net, input = models\[modelname\]()

opts = {inplace=true, mode='training'}
optnet = require 'optnet'

mem1 = optnet.countUsedMemory(net)

optnet.optimizeMemory(net,input,opts)
--optnet.optimizeMemory(net,input)

mem2 = optnet.countUsedMemory(net)

optnet.removeOptimization(net)

mem3 = optnet.countUsedMemory(net)

print('Before optimization        : '.. mem1.total_size/1024/1024 .. ' MBytes')
print('After optimization         : '.. mem2.total_size/1024/1024 .. ' MBytes')
print('After removing optimization: '.. mem3.total_size/1024/1024 .. ' MBytes')
```

**Comment by fmassa** [comment]
There are a couple of problems with your snippet, which is due to the fact that I haven't updated the README, sorry for the trouble.

First, to estimate the amount of memory used (including the output buffers), you first need to run your network once with the same input, if not you won't be counting the amount of memory due to the outputs.
Second, you are using the `training` mode optimization but only evaluating the network for the forward pass. Try running `forward`/`backward` first before every memory count, the results should be different than what you posted.

I'll update the README
