### ISSUE TITLE
Can not visualize siamese networks

### ISSUE THREAD

**Issue by WERush** [fmassa/optimize-net#29]
Hi, i want to visualize a simple siamese network. But the optnet.graphgen reports a issue -- "graphgen.lua:171: Parent node inexistant for module nn.SpatialConvolution(3 -> 16, 3x3, 1,1, 1,1)"
I can not figure out the error and i searched it on google but got no useful information.

The total code is shown as following:
```lua
local generateGraph = require 'optnet.graphgen'

local model = nn.Sequential()
-- model:add(nn.Reshape(32, 3, 224, 224))
model:add(nn.SpatialConvolution(3, 16, 3, 3, 1, 1, 1))
model:add(nn.ReLU())
model:add(nn.SpatialMaxPooling(2, 2))

model:add(nn.SpatialConvolution(16, 32, 3, 3, 1, 1, 1))
model:add(nn.ReLU())
model:add(nn.SpatialMaxPooling(2, 2))

model:add(nn.SpatialConvolution(32, 32, 3, 3, 1, 1, 1))
model:add(nn.ReLU())
model:add(nn.SpatialMaxPooling(2, 2))

model:add(nn.Reshape(32*28*28))
model:add(nn.Linear(32*28*28, 512))
model:add(nn.ReLU())
model:add(nn.Linear(512,128))
model:add(nn.ReLU())
model:add(nn.Linear(128,10))

siamese_net = nn.ParallelTable()
siamese_net:add(model)
siamese_net:add(model:clone('weight', 'bias', 'gradWeight', 'gradBias')) 

-- 2. full model to train, the input will be Tensor with shape (2, channel, height, width)
model_full = nn.Sequential()
model_full:add(nn.SplitTable(2)) 
model_full:add(siamese_net)
-- model_full:add(nn.PairwiseDistance(2))
print (model_full)

local input = torch.Tensor(32, 2, 3, 224, 224)

graphOpts = {
displayProps =  {shape='ellipse',fontsize=14, style='solid'},
nodeData = function(oldData, tensor)
  return oldData .. '\n' .. 'Size: '.. tensor:numel()
end
}

graph.dot(generateGraph(model_full, input, graphOpts))

```

**Comment by fmassa** [comment]
Hi,

This is related to issue https://github.com/fmassa/optimize-net/issues/6 , and even though a fix is pending in https://github.com/fmassa/optimize-net/pull/10 , I'm not sure it's a good fix as it can have side effects.

You can visualize siamese networks with `optnet`, but for that you need to replace a few modules in your model definition.
For example, instead of using the `nn.SplitTable` and passing a tensor as an argument, you should instead pass a table containing two tensors. This doesn't affect the computations of the network, but avoid creating a new tensor which can't be handle by `optnet` at the moment.

[Here is an example](https://github.com/fmassa/optimize-net/blob/master/models.lua#L72-L95) of a siamese network with the changes I mentioned that works with `optnet`.

**Comment by WERush** [comment]
Thanks, it works.
